### ISSUE TITLE
[FEATURE] Improvement in readme.md

### ISSUE THREAD

**Issue by shreyaansjain06** [DesignSystemsOSS/thedesignsystems#35]
### ⭐ Suggestion

readme.md need some contributing guidelines on how to start with it i can do this if you assign this issue to me

Thanks

**Comment by Vishrut-Arora** [comment]
Can I work on this?

**Comment by shreyaansjain06** [comment]
i asked for this first so it should be given to me @Vishrut-Arora  you can see some other issue

**Comment by Vishrut-Arora** [comment]
> i asked for this first so it should be given to me @Vishrut-Arora you can see some other issue

No problem :)

**Comment by yashsehgal** [comment]
It's good that you've mutually decided who will be getting the assignment 😄 

Also @shreyaansjain06, I am closing this issue as of now because there's already an issue related to the README file
Please do refer to #27
